import { discoverActor } from "./remoteActor.js";
import { sanitizeDescriptionHtml } from "./descriptionHtml.js";
import { logger } from "../logger.js";

// BookWyrm has no site-wide "what's trending" endpoint (confirmed via
// its own routing when Explore-server support for other platforms was
// researched — see federation/exploreDispatch.ts's sibling fetchers),
// but a specific, already-known user's outbox is a real, public, paginated
// OrderedCollection — confirmed live against bookwyrm.social. This is
// the read-a-known-person's-activity half of BookWyrm support, not a
// server-discovery feature.
export interface BookwyrmActivityItem {
  // The item's own AP id — also the human-browsable page on the
  // BookWyrm instance (confirmed live: unlike Ghost, BookWyrm doesn't
  // separate a machine id from a human url for these).
  id: string;
  contentHtml: string;
  bookTitle: string | null;
  bookCoverUrl: string;
  publishedAt: string;
}

async function fetchJson(url: string): Promise<Record<string, unknown> | null> {
  try {
    const response = await fetch(url, { headers: { Accept: "application/activity+json" } });
    if (!response.ok) return null;
    return (await response.json()) as Record<string, unknown>;
  } catch (err) {
    logger.warn({ err, url }, "bookwyrm activity fetch failed");
    return null;
  }
}

// Fetches a BookWyrm user's recent reading activity — "started
// reading"/"finished reading" notices, comments, and quotations, each
// auto-generated by BookWyrm as a plain AP Note. Every one of those
// (confirmed live across all three kinds) carries the book's cover as
// an `attachment` Document; a plain social reply in the same outbox
// never does. That presence, not the item's URL-path naming (which
// isn't part of the AP object itself), is what's used below to tell
// "book stuff" apart from everything else a BookWyrm outbox also
// contains — the only filter BookWyrm's real API shape actually
// supports.
export async function fetchBookwyrmActivity(
  handle: string,
  limit = 20,
): Promise<BookwyrmActivityItem[] | null> {
  const actor = await discoverActor(handle);
  if (!actor?.outbox) return null;

  const outbox = await fetchJson(actor.outbox);
  const firstPageUrl = typeof outbox?.first === "string" ? outbox.first : null;
  if (!firstPageUrl) return null;

  const page = await fetchJson(firstPageUrl);
  const items = Array.isArray(page?.orderedItems) ? (page!.orderedItems as Record<string, unknown>[]) : null;
  if (!items) return null;

  const results: BookwyrmActivityItem[] = [];
  for (const item of items) {
    if (results.length >= limit) break;
    if (item.type !== "Note" || typeof item.id !== "string" || typeof item.content !== "string") continue;

    const attachments = Array.isArray(item.attachment) ? item.attachment : [];
    const cover = attachments.find(
      (a) => typeof a === "object" && a !== null && typeof (a as { url?: unknown }).url === "string",
    ) as { url: string; name?: unknown } | undefined;
    if (!cover) continue;

    results.push({
      id: item.id,
      contentHtml: sanitizeDescriptionHtml(item.content),
      bookTitle: typeof cover.name === "string" ? cover.name : null,
      bookCoverUrl: cover.url,
      publishedAt: typeof item.published === "string" ? item.published : new Date().toISOString(),
    });
  }
  return results;
}
